#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(PSYCHIC_NOISE) \
    F(DRAGON_CLAW) \
    F(FLAME_CHARGE) \
    F(EARTH_POWER) \
    F(DRAGON_TAIL) \
    F(ICICLE_SPEAR) \
    F(LIFE_DEW) \
    F(DRAIN_PUNCH) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(NATURAL_GIFT) \
    F(STEEL_WING) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(BULLDOZE) \
    F(FOCUS_ENERGY) \
    F(GIGA_DRAIN) \
    F(WILL_O_WISP) \
    F(DEFOG) \
    F(SOLAR_BEAM) \
    F(ROCK_SLIDE) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(GRASS_KNOT) \
    F(STEEL_BEAM) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(MIST) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(SWAGGER) \
    F(SCALE_SHOT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(ROLE_PLAY) \
    F(ROCK_BLAST) \
    F(TORMENT) \
    F(SMART_STRIKE) \
    F(MAGICAL_LEAF) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(AERIAL_ACE) \
    F(ELECTROWEB) \
    F(SMACK_DOWN) \
    F(TAILWIND) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(ICE_PUNCH) \
    F(MEGA_PUNCH) \
    F(POISON_JAB) \
    F(SHADOW_PUNCH) \
    F(TEMPER_FLARE) \
    F(STOMPING_TANTRUM) \
    F(CHILLING_WATER) \
    F(ICY_WIND) \
    F(HYPER_VOICE) \
    F(SOLAR_BLADE) \
    F(WEATHER_BALL) \
    F(NIGHT_SHADE) \
    F(PARABOLIC_CHARGE) \
    F(NATURE_POWER) \
    F(CURSE) \
    F(TRAILBLAZE) \
    F(POUNCE) \
    F(FIRE_FANG) \
    F(ICE_FANG) \
    F(THUNDER_FANG) \
    F(POISON_FANG) \
    F(LEECH_LIFE) \
    F(IRON_TAIL) \
    F(THUNDER_WAVE) \
    F(LOW_SWEEP) \
    F(MUD_SHOT) \
    F(COVET) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
